version: "3.3"
services: 
  mysql.db.server:
    image: mysql:5.7
    container_name: mysql.db.server
    environment:
      - LANG=C.UTF-8
      - MYSQL_ROOT_PASSWORD=ssmdocker
      - MYSQL_USER=ssmdocker
      - MYSQL_PASSWORD=ssmdocker
    tmpfs:
      - /mysql/tmp/
    volumes:
      - D:\data\musql\data:/var/lib/mysql
    ports:
      - 3306:3306
