version: "3.3"
services: 
  ssmdocker.server:
    image: ssmdocker:latest
    container_name: ssmdocker.server
    ports:
      - 8081:8081
    depends_on: 
      - mysql.db.server
        
  mysql.db.server:
    image: mysql:v1
    container_name: mysql.db.server
    environment:
      - LANG=C.UTF-8
      - MYSQL_ROOT_PASSWORD=ssmdocker
      - MYSQL_USER=ssmdocker
      - MYSQL_PASSWORD=ssmdocker
    tmpfs:
      - /mysql/tmp/
    volumes:
      - D:\data\mysql\docker-data:/var/lib/mysql
    ports:
      - 3306:3306
