server:
  port: 8081
  
logging: 
  config: classpath:logback-spring.xml
  
liquibase:
  change-log: classpath:master.xml
  enabled: true
  drop-first: false
  createDatabaseIfNotExist: true
  user: ssmdocker
  pssword: ssmdocker
  url: jdbc:mysql://localhost:3306/test